FROM zhiqiangwang/gvm:latest

RUN apt-get update && apt-get install -y zip \ 
    && apt-get clean  \
    && rm -rf /var/lib/apt/lists/*

ADD cnb-build.sh /
RUN chmod +x /cnb-build.sh

ENTRYPOINT ["/cnb-build.sh"]

CMD []